version: 2
jobs:
  build:
    machine: true
    working_directory: '~/nuxt-travis-digital'
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      # build the application image
      - run: docker build -t $DOCKER_USER/promo .

      # deploy the image
      - run: docker push $DOCKER_USER/promo

      # deploy on digital ocean
      # - deploy:


workflows:
  version: 2
  build:
    jobs:
      - build
